resources:
- repo: self

queue:
  name: Hosted VS2017

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'custom'
    custom: 'msbuild'
    projects: TSWrangler.proj
    arguments: '-v:n -t:Setup;Build -p:Configuration=Release'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: src/TSWrangler.Build.Sdk.csproj
    buildProperties: 'Configuration=Release;BuildNumber=$(Build.BuildNumber)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: TSWrangler.Build.Sdk'
  inputs:
    artifactName: 'TSWrangler.Build.Sdk'