resources:
- repo: self

queue:
  name: Hosted VS2017

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet msbuild'
  inputs:
    command: 'custom'
    custom: 'msbuild'
    projects: ChocolateTS.proj
    arguments: '-v:n -t:Setup;Build -p:Configuration=Release;BuildNumber=$(Build.BuildNumber)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: ChocolateTS.Build.Sdk'
  inputs:
    artifactName: 'ChocolateTS.Build.Sdk'