resources:
- repo: self

queue:
  name: Hosted VS2017

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: ChocolateTS.proj
    arguments: '/v:n /p:Configuration=Release'
