resources:
- repo: self

queue:
  name: Hosted VS2017

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet msbuild'
  inputs:
    projects: ChocolateTS.proj
    arguments: '-v:n -t:Setup;Build -p:Configuration=Release'
